CREATE TABLE urls (
    id BIGINT PRIMARY KEY,
    original_url VARCHAR(2048) NOT NULL UNIQUE,
    short_code VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    click_count BIGINT NOT NULL DEFAULT 0
);
